"""Single source for the backlog. Run: python3 docs/backlog_source.py
Writes BACKLOG.md (repo root) and docs/backlog.csv."""
import csv, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent

EPICS = {
    "0": ("Foundation", "Make the POC a safe base: tests, CI, migrations, shared types."),
    "1": ("Accounts & memberships", "Real users, tiers, payments, and server-enforced access."),
    "2": ("Chat & moderation", "The core chat experience and the tools to keep it usable."),
    "3": ("Live via YouTube", "Watch live in-platform with YouTube/Rumble chat merged in, then auto-archive."),
    "4": ("Mobile apps", "iOS and Android with background audio, PiP, gestures, and IAP."),
    "5": ("Owned live & audio", "Platform-independent live, audio-only, and podcast feeds."),
    "6": ("Engagement & AI", "XP, badges, captions, recaps, call-ins."),
    "7": ("Studio & analytics", "Creator tools and audience insight."),
    "8": ("Library & community", "Videos dashboard, playlists, up next, posts, and live presence."),
}

# id, phase, priority, size, title, user story, acceptance criteria, depends on
S = [
# ---------------- 0 Foundation ----------------
("001", 0, "Must", "M", "Test harness",
 "As the developer, I want automated tests so Claude Code can change things safely.",
 ["`npm test` runs server and web tests from the repo root",
  "Server tests run against a disposable Postgres (`DATABASE_URL_TEST`) and reset it per run",
  "Covered: sign-in, tier gating on `/videos/:id`, chat window query, chat post + rate limit, WS broadcast",
  "Web: at least one render test each for Home, Watch (locked + unlocked), ChatPanel"], []),
("002", 0, "Must", "S", "Lint and format",
 "As the developer, I want consistent code style enforced automatically.",
 ["ESLint + Prettier configured for server and web", "`npm run lint` and `npm run format` at root", "Existing code passes lint"], []),
("003", 0, "Must", "M", "Database migrations",
 "As the developer, I want versioned schema changes so production data is never at risk.",
 ["node-pg-migrate installed; baseline migration equals current `schema.sql`",
  "Migrations run as Render pre-deploy command, not on app boot",
  "`npm run migrate:create <name>` documented in CLAUDE.md", "`schema.sql` removed or marked historical"], []),
("004", 0, "Should", "L", "TypeScript and shared package",
 "As the developer, I want shared types across server, web, and mobile so contracts can't drift.",
 ["`packages/shared` exports types for User, Video, ChatMessage, WS events, and a typed API client",
  "Server and web compile with `tsc --noEmit` in CI", "No behavior change; all tests pass"], ["001", "002"]),
("005", 0, "Must", "S", "CI pipeline",
 "As the developer, I want every PR checked before merge.",
 ["GitHub Actions runs lint, test (with Postgres service), and build on PRs to main", "Status check required to merge"], ["001", "002"]),
("006", 0, "Must", "S", "Extract YouTube replay parser",
 "As the developer, I want the chat replay parser as a tested module so live ingest can reuse it.",
 ["Parser lives in `server/src/ingest/youtubeReplay.js` with pure functions",
  "Fixture-based tests cover text, emoji, super chat, membership, negative offsets",
  "Import script uses the module; behavior unchanged"], ["001"]),
("007", 0, "Should", "S", "Structured logging",
 "As the operator, I want useful logs when something breaks in production.",
 ["pino logger with request id per HTTP request", "Errors logged with stack; no secrets or tokens logged"], []),
("008", 0, "Should", "S", "Staging environment",
 "As the product owner, I want to review changes before they reach JimBob's audience.",
 ["Separate Render service + database for staging deployed from `staging` branch", "Documented in README"], ["003"]),

# ---------------- 1 Accounts & memberships ----------------
("101", 1, "Must", "L", "Real authentication",
 "As a viewer, I want a real account so my identity, tier, and history are mine.",
 ["Self-hosted auth (ADR-006) with email + password (magic link, Google, and Apple sign-in are MBJ-110)",
  "Users choose a unique username at signup (3–32 `[A-Za-z0-9_]`)",
  "POC `/session` endpoint and `session_token` column removed",
  "Tier can no longer be self-selected"], ["003"]),
("102", 1, "Must", "S", "Roles and Studio access",
 "As JimBob, I want only me and my mods to reach Studio and mod tools.",
 ["`users.role` = viewer | mod | admin", "`/api/studio/*` and `/api/mod/*` return 403 for viewers",
  "Studio nav hidden for viewers", "Admin can promote/demote mods in Studio"], ["101"]),
("103", 1, "Must", "M", "Signed playback URLs",
 "As JimBob, I want paid videos to be unwatchable without the right tier, even with a copied link.",
 ["Gated videos have `requireSignedURLs` enabled on Stream",
  "API returns a short-lived signed token URL only to entitled users",
  "Free videos stay unsigned", "Import script sets the flag based on `--tier`"], ["101"]),
("104", 1, "Must", "L", "Web subscriptions and entitlements",
 "As a viewer, I want to subscribe to Plus or Premium on the web.",
 ["Stripe Checkout for Plus and Premium (monthly; annual optional)",
  "RevenueCat receives Stripe purchases; webhook updates `entitlements`",
  "`users.tier` derived from active entitlements; expires correctly on cancel/lapse",
  "Webhooks verified by signature and idempotent"], ["101"]),
("105", 1, "Must", "M", "Pricing page and upsell",
 "As a free viewer, I want to see what paid tiers include and upgrade in one step.",
 ["Pricing page shows the tier matrix from the PRD", "Locked video screen links to upgrade with that tier preselected",
  "After purchase, the user returns to the video and it plays"], ["104"]),
("106", 1, "Must", "M", "Account settings",
 "As a member, I want one place to manage my profile, sign-in, notifications, membership, and privacy.",
 ["`/account` (signed in only) with sections: Profile, Sign-in and security, Notifications, Membership, Privacy and data",
  "Profile links to the editor (MBJ-117); Sign-in and security holds password, email, devices, and sign-in methods (MBJ-113, MBJ-110)",
  "Notifications: per-type on/off for in-site, push, and email (replaces the scattered toggles)",
  "Membership shows tier, renewal date, and manage/cancel once MBJ-104 lands; before that it shows Free and what paid tiers include",
  "Account menu in the top bar links here; works at phone width"], ["101"]),
("107", 1, "Must", "S", "Owned email list",
 "As JimBob, I want my audience's contact info so no platform can take my audience away.",
 ["Marketing opt-in checkbox at signup, stored with timestamp",
  "Admin can export opted-in users as CSV from Studio", "Unsubscribe link handling documented",
  "Start from the existing Shopify newsletter list (export from Shopify customers who accepted marketing)"], ["101", "102"]),

("108", 1, "Must", "M", "Registration",
 "As a new viewer, I want to create an account in under a minute so I can chat, comment, and join.",
 ["`/join` page and a sign-up dialog anywhere an action needs an account (chat, comment, like); afterwards you land back where you were, with the action ready",
  "Fields: email, username, password (at least 10 characters, checked against known-leaked passwords); Google and Apple once MBJ-110 lands",
  "Username: unique ignoring case, 3–32 `[A-Za-z0-9_]`, live availability check with suggestions; reserved names blocked (jimbob, admin, mod, support, and staff names); banned words blocked",
  "\"I'm 13 or older\" checkbox; Terms and Privacy links; optional email-list opt-in (MBJ-107)",
  "Verification email with a link (expires in 24 h, can be re-sent); unverified accounts can watch and chat but can't tip, buy, or claim rewards",
  "Bot protection: Cloudflare Turnstile on the form, plus rate limits per IP and per email",
  "Errors say what went wrong and how to fix it (\"That username is taken — try jimbobfan_2\")",
  "Existing POC accounts are asked to add and verify an email the next time they sign in"], ["101", "114"]),
("109", 1, "Must", "M", "Payments API and receipts",
 "As a member, I want reliable billing; as JimBob, I want to see and manage payments.",
 ["Stripe webhooks (checkout, renewals, failures, refunds) update entitlements idempotently",
  "Members see payment history and receipts; Stripe customer portal to change card or cancel",
  "Studio: revenue, refunds, failed payments; test mode for staging",
  "Backup processor evaluated (PRD open question)"], ["104"]),
("110", 1, "Must", "M", "Easy sign-in and staying signed in",
 "As a viewer, I want to sign in with one tap and stay signed in on my devices.",
 ["Sign in with Google (also links YouTube for MBJ-215), Apple, X, and Facebook; email magic link as the no-password option",
  "Passkeys (Face ID / fingerprint / Windows Hello) instead of passwords",
  "Stay signed in: long-lived sessions that renew while used (e.g. 90 days), on web and the installed app",
  "Profile: see signed-in devices and sign out any of them; add or remove sign-in methods; merge an existing account",
  "Signing in from a notification or email link lands you where you were going",
  "Self-hosted auth library per ADR-006 (user records stay in our database)"], ["101"]),
("111", 1, "Must", "L", "Saved payment methods and a wallet",
 "As a member, I want to pay in one tap with a method I've saved; as JimBob, I want to keep as much of each payment as possible.",
 ["Saved methods on the profile: cards via Stripe, Apple Pay / Google Pay, PayPal (and Venmo), bank account (ACH); set a default, remove any",
  "One-tap tips, Bob Chats, and memberships with the default method; receipts in the profile",
  "Wallet (prepaid credits): add $10/$20/$50 once, then spend on Bob Chats and tips with no per-message fee",
  "Yearly membership option (one fee instead of twelve) with a discount",
  "Web checkout for everything where app-store rules allow; in-app purchase only where required",
  "A second processor ready (PayPal or other) in case one drops the account (PRD independence goal)"], ["104", "112"]),
("112", 1, "Must", "S", "Payments and fees decision (ADR)",
 "As JimBob, I want the lowest-fee setup that still makes paying easy and keeps me independent.",
 ["Compare with current published rates: Stripe (cards, Link, ACH), PayPal/Venmo, Shopify Payments, bank transfers, and crypto processors; include app-store fees for the phone apps",
  "Model real money with JimBob's numbers: memberships, Bob Chats/tips by size, merch orders, and the current Shopify plan and apps",
  "Decide merch: keep Shopify, or move to our own checkout (Stripe) with a print-on-demand partner for fulfilment; show the yearly saving and the work involved",
  "Record the decision as an ADR and update MBJ-104, MBJ-109, MBJ-111, and MBJ-807"], []),
("113", 1, "Must", "M", "Password reset and email change",
 "As a member, I want to get back into my account if I forget my password, and keep my email up to date.",
 ["\"Forgot password?\" sends a reset link (one use, expires in 1 h); the response never reveals whether the email has an account",
  "Resetting or changing the password signs out every other device",
  "Change email: confirm with the password, verify the new address, and notify the old one with a link to undo within 7 days",
  "Change password from Account settings (current password required)",
  "Rate limits on reset and change requests; every change is logged for the member's security history"], ["101", "114"]),
("114", 1, "Must", "S", "Sending email (ADR)",
 "As JimBob, I want account emails to arrive from my own domain and not land in spam.",
 ["Pick a transactional email provider and record it as an ADR with the monthly cost at 1k, 10k, and 50k members (compare Resend, Postmark, Amazon SES)",
  "Sender on JimBob's domain (e.g. hello@) with SPF, DKIM, and DMARC set up",
  "Plain branded templates: verify email, reset password, email changed, new sign-in, account deleted",
  "Bounces and complaints recorded; bounced addresses stop getting mail",
  "Server tests never send real email (a stub records what would have been sent)"], []),
("115", 1, "Should", "S", "Welcome steps",
 "As a new member, I want a quick start that makes the site mine without forcing anything.",
 ["After sign-up: add an avatar, pick notifications (live alerts on by default), link YouTube (MBJ-215), see membership options",
  "Every step can be skipped; a checklist on the profile shows what's left",
  "Ends on the page they signed up from, or the latest video"], ["108"]),
("116", 1, "Should", "M", "Public profile",
 "As a viewer, I want to see who someone in chat is; as a member, I want a page that shows I'm part of the community.",
 ["`/@username` page: avatar, display name, bio, links, joined date, tier badge, and badges/level once MBJ-602 lands",
  "Recent public activity: comments with the video and moment they're on (each opens the video there); chat messages only if the member allows it",
  "Tapping a name or avatar in chat or comments opens a small profile card with \"View profile\" and \"Mention\"",
  "Linked YouTube/Rumble names shown once verified (MBJ-215)",
  "Anyone can view profiles, signed in or not; they aren't in search results (noindex) unless the member turns that on",
  "Banned members' profiles show only the username"], ["101"]),
("117", 1, "Should", "M", "Edit profile",
 "As a member, I want to choose how I look to everyone else on the site.",
 ["Avatar: upload (JPEG/PNG/WebP up to 5 MB), crop to a circle, resized to small and large sizes; a default avatar with initials and a color until then",
  "Display name (up to 40 characters, shown next to the username), bio (up to 300 characters), up to 3 links",
  "Username change once every 30 days; the old name stays reserved for 30 days and old profile links redirect",
  "Avatars, names, and bios go through the same banned-word filter as chat; mods can reset them from Studio",
  "Changes show everywhere (chat, comments, profile) without a reload"], ["116"]),
("118", 1, "Must", "M", "Download my data and delete my account",
 "As a member, I want to take my data with me or leave for good; as JimBob, I want the apps to pass store review.",
 ["Download my data: profile, comments, chat messages, likes, watch history, and payments as a JSON file",
  "Delete account from Account settings with the password (or a fresh sign-in); required in the phone apps by Apple and Google",
  "30 days to change your mind (signing in cancels it), then the account is erased; paid memberships are cancelled first",
  "Chat messages and comments stay in replays as \"Deleted user\" so conversations still make sense; an option also removes them",
  "Confirmation email at request and at erasure"], ["101", "114"]),
("119", 1, "Should", "S", "Block and mute",
 "As a member, I want to stop seeing someone who bothers me.",
 ["Block from the profile card or profile page; unblock from Account settings",
  "A blocked member's chat messages, comments, and mentions are hidden for you; they can't mention you or reply to you",
  "Mute (hide their messages) without them being able to tell",
  "Blocking never hides mods or JimBob",
  "Report a member (from the profile card, a message, or a comment) with a reason; reports land in a queue mods work from Studio (MBJ-204)"], ["101"]),
# ---------------- 2 Chat & moderation ----------------
("201", 1, "Should", "M", "Chat replay polish",
 "As a viewer, I want chat that feels as good as YouTube's.",
 ["\"Jump to latest\" button appears when scrolled up; resumes auto-scroll",
  "Hovering a message shows its video timestamp; clicking seeks the player there",
  "On WebSocket reconnect, missed messages are fetched since the last id"], []),
("202", 1, "Should", "M", "@mention autocomplete and notifications",
 "As a member, I want to know when someone mentions me.",
 ["Typing `@` suggests recent chatters in this video", "Mentioned native users get an in-app notification (bell with count)",
  "Clicking a notification opens the video at that message's timestamp"], ["101"]),
("203", 1, "Should", "M", "Upvotes and top questions",
 "As a viewer, I want to upvote good messages; as JimBob, I want the best questions surfaced.",
 ["One vote per user per message; toggle to remove", "Vote counts update live via WS `vote` event",
  "\"Top questions\" tab lists messages containing `?` ordered by votes"], ["101"]),
("204", 1, "Must", "L", "Moderation tools",
 "As a mod, I want to hide messages and remove bad actors quickly.",
 ["Mods can hide a message, time out a user (1/5/60 min), or ban a user",
  "Room modes: open, slow (N seconds), members-only; broadcast via WS `room`",
  "Hidden messages disappear for all viewers in real time (WS `hide`) but remain in the database",
  "Every action logged in `mod_actions` and visible in Studio"], ["102"]),
("205", 3, "Should", "M", "Redis pub/sub and rate limits",
 "As the operator, I want chat to work across multiple instances and a separate ingest worker.",
 ["Render Key Value added to `render.yaml`", "Room fan-out via Redis pub/sub", "Rate limits stored in Redis",
  "Works with 2 web instances in a load test of 1,000 sockets"], ["001"]),
("206", 1, "Should", "M", "Managed filters and spam detection",
 "As a mod, I want to manage banned terms and have obvious spam held automatically.",
 ["`banned_terms` editable in Studio replaces the env var", "Automated classifier holds likely spam/toxicity for review",
  "Mods can approve or reject held messages"], ["204"]),
("207", 1, "Should", "L", "Native tipped messages (web)",
 "As a member, I want to tip with a highlighted message like a Super Chat.",
 ["Fixed tip amounts via Stripe", "Message posts only after payment confirmation (webhook)",
  "Paid message pinned for a duration scaled by amount; WS `pin` event", "Tips appear in Studio revenue",
  "Bring in Bob Chats (today sold as a product on the Shopify store): shown and pinned like Super Chats, counted in the same totals"], ["104"]),
("208", 1, "Could", "M", "Chat search in Studio",
 "As JimBob, I want to find what people said.",
 ["Search by text, author, source, date range, video", "Results link to the video at that timestamp"], ["102"]),
("209", 1, "Should", "S", "Tier-based chat limits",
 "As JimBob, I want free chatters slowed down and members rewarded.",
 ["Free users: slow mode per PRD; Plus/Premium: normal rate", "Tier badge shown next to native usernames"], ["104"]),

("210", 1, "Must", "M", "Video comments",
 "As a viewer, I want YouTube's comments and our members' comments under each video, like on YouTube.",
 ["Import pulls YouTube comments with replies, likes, pinned, and creator flag; re-import refreshes likes",
  "Comments section under the video: Top/Newest sort, 20 threads per page, replies collapsed per thread",
  "Signed-in members post comments and replies (one level); tier-gated like chat; rate limited",
  "YT/JB source tags and a Creator badge distinguish where each comment came from"], ["001"]),
("211", 1, "Must", "L", "One conversation across live chat, replay chat, and comments",
 "As a viewer, I want to join the stream's conversation after it ended without losing what was said live or what each reply answers.",
 ["Chat marks live vs replay messages; Live only (default) / Live + replay toggle with a count of hidden later posts",
  "Chat and comment replies quote the exact message they answer; tapping the quote shows the original",
  "Tap a name to reply with @name; typing @ suggests names from the video",
  "Comments can carry a moment in the video and appear as bubbles in the chat feed; YouTube comments take the first typed time",
  "Typed times in comments are clickable; a chat bubble opens its whole thread"], ["210"]),
("212", 1, "Must", "S", "Resume where you left off",
 "As a viewer, I want videos to pick up where I stopped, on any device.",
 ["Position saved every 10s and on leaving the page; on the account when signed in, in the browser otherwise",
  "Reopening resumes (past 10s, not in the last 30s) with Resumed from mm:ss and a Start over button",
  "?t=<seconds> links start at that time", "Video cards show a watched progress bar"], []),
("213", 1, "Must", "M", "Installable web app (PWA)",
 "As a viewer, I want to add the site to my phone's Home Screen and use it like an app.",
 ["Web app manifest and icons; installable in Chrome/Edge (no installability errors)",
  "Service worker caches the app shell; API, WebSockets, and video are never cached",
  "Install app button where the browser supports it; one-time Share -> Add to Home Screen hint on iPhone"], []),
("214", 1, "Must", "M", "Push notifications (web)",
 "As a member, I want a notification on my phone when someone mentions or replies to me, even with the app closed.",
 ["Web Push with VAPID keys; subscribe/unsubscribe endpoints; dead subscriptions removed",
  "Turn on from the bell; iPhone asks to add to Home Screen first",
  "Tapping a notification opens the video at that moment (and the thread for comments)",
  "Needs VAPID_PRIVATE_KEY set on Render"], ["202", "213"]),
("215", 1, "Should", "M", "Link YouTube and Rumble names to a profile",
 "As a member, I want my YouTube/Rumble chat history and mentions tied to my site account.",
 ["Account settings: a member enters their YouTube @handle (or Rumble name); a moderator confirms it in Studio",
  "The YouTube channel id is found from imported chat and comments by handle, so links survive renames",
  "Rumble names verified by hand in Studio until Rumble chat ingest exists",
  "Linked YouTube messages show the site name and tier badge; @mentions of the YouTube handle notify the member"], ["202"]),
("216", 1, "Should", "S", "Count one view per viewer",
 "As JimBob, I want view counts I can trust.",
 ["A view counts once per viewer per video per day (account, or browser for signed-out)",
  "Refreshes and resumed sessions don't add views"], []),
# ---------------- 3 Live via YouTube ----------------
("301", 3, "Must", "M", "Live video model and live page",
 "As a viewer, I want to watch JimBob live without leaving the platform.",
 ["`videos.status` and `videos.source` added (see DATA_MODEL)", "Live page embeds the YouTube IFrame player for the active broadcast",
  "\"Live now\" banner on Home while a stream is live", "`GET /api/live/current` returns the live video or null"], ["003"]),
("302", 3, "Must", "L", "YouTube live chat ingest worker",
 "As a viewer, I want YouTube chat in the platform in real time.",
 ["Render background worker; JimBob authorizes his channel once via OAuth",
  "Detects live broadcast start/end", "Polls chat at YouTube's interval; inserts with `offset_ms = publishedAt − actualStartTime`",
  "Idempotent; persists page token in `ingest_cursors`; survives restarts without gaps or duplicates",
  "Publishes new messages to the video's room"], ["301", "205", "006"]),
("303", 3, "Must", "M", "Live chat mode in the UI",
 "As a viewer, I want live chat to behave like live chat, not replay.",
 ["Live videos render all incoming messages (no playhead filtering)", "Native posts use server-computed `offset_ms`",
  "After the stream is archived, the same chat replays in sync"], ["302"]),
("304", 3, "Must", "M", "Auto-archive finished streams",
 "As JimBob, I want every live stream saved to my own storage automatically.",
 ["When a broadcast ends, a job downloads the VOD and uploads it to Stream",
  "Video row switches to archived; tier default configurable", "Failure retries and alerts in logs"], ["302"]),
("305", 3, "Should", "L", "Post to YouTube chat from the platform",
 "As a member with a YouTube account, I want my messages to appear in YouTube's chat too.",
 ["User links YouTube via Google OAuth", "Posts go to YouTube via `liveChatMessages.insert` and to native chat, de-duplicated",
  "Quota usage tracked daily; when exhausted, posts fall back to native-only with a notice"], ["101", "302", "306"]),
("306", 3, "Must", "S", "Google API verification and quota request",
 "As the product owner, I want Google approvals in place before live features need them.",
 ["OAuth consent screen verified for YouTube scopes", "Quota increase requested with expected usage",
  "Non-code task — owner: Ruben. Start during Phase 1."], []),
("307", 3, "Should", "M", "Rumble chat and Rants ingest",
 "As a viewer, I want Rumble chat merged into the same feed.",
 ["Worker polls Rumble Live Stream API with JimBob's key", "Messages stored with `source = rumble`; Rants as `kind = paid`",
  "Rumble tag shown in chat"], ["302"]),
("308", 3, "Should", "M", "Moderation reaches YouTube",
 "As a mod, I want one set of tools for both chats.",
 ["Hiding a YouTube-sourced message also deletes it on YouTube", "Banning a YouTube author bans them on YouTube",
  "Actions use JimBob's OAuth token and are logged"], ["204", "302"]),
("309", 3, "Should", "S", "Configurable live source",
 "As JimBob, I want to switch live platforms without an app update.",
 ["Live source per video: youtube | rumble | owned", "Clients pick the player from the API response"], ["301"]),

# ---------------- 4 Mobile ----------------
("401", 2, "Must", "L", "Expo app scaffold",
 "As a viewer, I want the platform as a phone app.",
 ["`mobile/` Expo app in the workspace using `packages/shared`", "Sign-in, Home, Watch, Account screens",
  "Runs on iOS simulator and Android emulator"], ["004", "101"]),
("402", 2, "Must", "M", "Mobile player and gestures",
 "As a mobile viewer, I want YouTube-quality player controls.",
 ["expo-video HLS playback", "Double-tap left/right ±10s with visual feedback", "Long-press 2× while held",
  "Pinch to zoom (1×–3×)"], ["401"]),
("403", 2, "Must", "M", "Background audio, lock screen, PiP",
 "As a passive listener, I want to lock my phone and keep listening.",
 ["Audio continues with screen locked and app backgrounded", "Lock-screen/notification controls with title and artwork",
  "PiP starts automatically when leaving the app while playing", "Listen-only toggle hides video"], ["402"]),
("404", 2, "Must", "M", "Mobile chat",
 "As a mobile viewer, I want to read and post chat.",
 ["Chat panel synced to playback (replay) and live mode", "Catch-up fetch after returning from background"], ["401"]),
("405", 2, "Should", "M", "Push notifications",
 "As a member, I want to know when JimBob goes live or someone mentions me.",
 ["Expo push for: live now, @mentions, tip replies", "Per-type opt-out in Account"], ["401", "202"]),
("406", 2, "Must", "L", "In-app subscriptions and tips",
 "As a mobile viewer, I want to subscribe and tip in the app.",
 ["RevenueCat offerings for Plus and Premium on iOS and Android", "Consumable tip products",
  "Entitlements shared with web purchases"], ["104", "401"]),
("407", 2, "Must", "M", "Store release",
 "As JimBob, I want the app in both stores.",
 ["EAS Build/Submit configured", "TestFlight and Play internal testing live", "Store listings and privacy disclosures complete"], ["403", "406"]),

# ---------------- 5 Owned live & audio ----------------
("501", 4, "Must", "L", "Owned live ingest to R2",
 "As JimBob, I want a live stream no platform can shut off.",
 ["MediaMTX on a VPS accepts RTMP/SRT from OBS", "ffmpeg outputs 720p/480p + audio-only HLS to R2",
  "Served via a Cloudflare domain; plays in web and mobile", "Runbook in `docs/runbooks/owned-live.md`"], ["309"]),
("502", 4, "Must", "M", "Audio-only renditions",
 "As a passive listener, I want listen mode to use far less data.",
 ["Live: audio-only HLS from 501", "VOD: job produces AAC HLS per video to R2", "Listen-only mode switches to the audio playlist"], ["501"]),
("503", 4, "Should", "M", "Podcast feeds",
 "As a listener, I want streams in my podcast app.",
 ["Public RSS feed of free episodes", "Private per-member tokenized feed including paid episodes; revoked on lapse",
  "Feeds validate in Apple Podcasts"], ["502", "104"]),
("504", 4, "Should", "M", "Restream to YouTube and Rumble",
 "As JimBob, I want to stream once and reach every platform.",
 ["Ingest forwards to YouTube and Rumble RTMP targets", "Targets configurable in Studio"], ["501"]),
("505", 4, "Should", "M", "Owned live recordings",
 "As JimBob, I want owned streams archived automatically.",
 ["Live segments assembled into a VOD after the stream", "Chat replays in sync"], ["501"]),

("506", 4, "Should", "M", "Move stored video to R2 (ADR-010)",
 "As JimBob, I want my library in plain files I control, at a fraction of Stream's storage cost.",
 ["Decision recorded on ADR-010", "Import transcodes to an HLS ladder + audio-only with ffmpeg and uploads to R2",
  "Gated videos protected by a short-lived token checked at the edge", "Existing Stream videos migrated; captions kept (transcripts table)"], []),
# ---------------- 6 Engagement & AI ----------------
("601", 5, "Must", "S", "Watch and listen tracking",
 "As JimBob, I want to know who actually watches and listens.",
 ["Client heartbeat every 60s while playing (video or listen-only)", "Stored in `watch_sessions` with mode"], ["101"]),
("602", 5, "Should", "M", "XP, levels, badges",
 "As a regular, I want my loyalty visible in chat.",
 ["XP from watch/listen time, messages, and upvotes received; tier multipliers per PRD",
  "Level and badge shown next to name in chat", "Anti-farming: idle tabs and duplicate messages earn nothing",
  "Activity badges for heavy chatters and commenters (e.g. bronze/silver/gold by messages and comments that others reply to or like), streaks for attending live, and a Regular badge; shown in chat, comments, and on profiles",
  "JimBob can create and award custom badges (e.g. Debate MVP, Founding member) from Studio"], ["601"]),
("603", 5, "Could", "S", "Leaderboards",
 "As a regular, I want to see where I rank.",
 ["Per-stream and all-time leaderboards", "Shown on watch page and in Studio"], ["602"]),
("611", 5, "Should", "M", "Watch-time rewards (e.g. a free t-shirt)",
 "As a loyal viewer, I want a real reward for the hours I spend watching and listening.",
 ["JimBob sets milestones and rewards in Studio (e.g. 100 hours watched → free t-shirt), with a monthly budget or a limit on claims",
  "Only real watching counts: playing video or Listen only, at most real time (2x speed doesn't double it), idle and background-muted tabs excluded, daily cap",
  "Progress bar on the viewer's profile and a notification when a reward unlocks",
  "Claiming a physical reward needs a verified account (MBJ-108); one per person per reward",
  "Delivered through the Shopify store: a one-time 100%-off code for the chosen shirt, so ordering, sizing, and shipping use the existing checkout",
  "Studio list of claims, with the ability to review and cancel suspicious ones"], ["601", "108", "807"]),
("612", 5, "Should", "M", "Supporter shout-outs",
 "As a supporter who super chats or Bob Chats, I want JimBob to see it and thank me.",
 ["Every super chat, Bob Chat, and tip goes into a shout-out queue in Studio during the stream, oldest first, with name, amount, and message; JimBob marks each one read",
  "Optional on-stream overlay (a browser source for OBS) that shows the current shout-out",
  "Paid messages are highlighted and pinned in chat (MBJ-207); the supporter gets a thank-you notification when JimBob reads it",
  "Supporter badge and a Supporters wall with top supporters this month (opt-in names)",
  "Shout-outs appear in the stream notes with the time JimBob answered (MBJ-605)"], ["207"]),
("613", 5, "Should", "L", "Ratings, moment reactions, and hotspots",
 "As a viewer, I want to rate a stream and mark the parts that are funny, interesting, or boring, and see what everyone else thought minute by minute.",
 ["Thumbs up / down on each video (counts shown; one vote per person, changeable)",
  "Moment reactions while watching: one tap (Funny, Interesting, Fire, Boring, Cringe) stamps the current moment; press-and-drag on the progress bar marks a stretch (e.g. a boring call-in from 2:04:00 to 2:19:30) with a reaction",
  "Hotspot strip over the progress bar: a minute-by-minute heatmap of reactions, colored by the strongest reaction, combined with chat activity; tapping a spike jumps there",
  "Optional \"skip marked-boring stretches\" and \"play the best parts\" (highest-rated minutes) modes",
  "Studio: per-video minute-by-minute chart of reactions and chat (with MBJ-702) to see what landed and what dragged",
  "Fair counting: signed-in viewers only, one reaction per kind per person per minute, stretches capped in length, and heavy one-person marking down-weighted",
  "Feeds the AI stream notes and tags (MBJ-605, MBJ-609): hotspots become suggested highlights and clips"], ["601"]),
("604", 5, "Should", "M", "Captions",
 "As a viewer, I want captions on stored videos.",
 ["Captions generated for each VOD (Stream captions or Whisper)", "Selectable in web and mobile players", "Transcript stored"], []),
("605", 5, "Should", "L", "AI stream notes (the facilitator)",
 "As a viewer or JimBob, I want notes for every stream like an AI meeting facilitator writes: what happened, who said what, and when.",
 ["After a stream is archived, a job reads the transcript, speaker labels (MBJ-608), chat, super chats and Bob Chats, and writes the notes",
  "Summary at the top; sections/chapters with titles and times that seek the player",
  "Key exchanges between speakers: each side's main points in a debate, with timestamps",
  "Money moments: every super chat, Bob Chat, and tip with who sent it, what they said, and whether/when JimBob answered it",
  "Questions from chat and guests, answered or not; follow-ups and promises made on stream (\"I'll look into that next week\")",
  "Chat pulse: busiest moments and what set them off",
  "JimBob can edit, hide, or regenerate before publishing; notes are members-only or public per video",
  "Cost per stream estimated and shown before running on the whole library (Claude API for the notes)"], ["604", "608"]),
("608", 5, "Should", "M", "Who's talking (speaker labels)",
 "As a viewer, I want the transcript to show who said each line.",
 ["Transcripts with speaker turns (diarization): Whisper + a diarization model, or a transcription service with speaker labels (decide by cost and accuracy)",
  "JimBob names each speaker once per stream in Studio (JimBob, guest names, callers); recurring guests are remembered",
  "Transcript panel on the watch page follows playback, shows speaker names, and each line seeks the video"], ["604"]),
("609", 5, "Should", "M", "Tags: sections, topics, people",
 "As a viewer, I want to find every moment about a topic or with a person across all streams.",
 ["Tags on moments and sections: topics (e.g. evolution, Orthodoxy), people who spoke, people mentioned, and chat users involved",
  "AI suggests tags from the notes (MBJ-605); JimBob and mods accept, edit, or add their own in Studio",
  "Topic and person pages: every tagged moment across streams, playable from that point",
  "Tags feed search (MBJ-610) and playlists (auto playlist per topic or guest)"], ["605"]),
("610", 5, "Should", "M", "Search inside streams",
 "As a viewer, I want to search what was said and jump straight to it.",
 ["Search across transcripts, chat, comments, notes, and tags; results show the line with its speaker and time",
  "Clicking a result opens the video at that moment (?t=)",
  "Postgres full-text search to start; filters by stream, speaker, date, and source (said on stream vs chat)"], ["604"]),
("606", 5, "Could", "XL", "Call-ins",
 "As a Premium member, I want to call in to the live show.",
 ["Premium users request to call; LiveKit green room", "Producer screens and approves", "Approved caller appears in OBS via browser source"], ["104", "301"]),
("607", 5, "Could", "L", "Polls and predictions",
 "As a viewer, I want to spend points and play along.",
 ["Mods create polls/predictions during a stream", "Viewers vote with points; results broadcast live"], ["602"]),

# ---------------- 7 Studio & analytics ----------------
("701", 1, "Must", "L", "Video management in Studio",
 "As JimBob, I want to upload, edit, replace, and delete videos without a terminal.",
 ["Upload a video file from the browser (resumable, straight to Cloudflare Stream or R2 per ADR-010) with progress; it appears once processing finishes",
  "Start a YouTube import from a URL (background job with status: downloading, uploading, processing, chat, comments, captions)",
  "Edit title, description, type (video/short/live), tier, publish date, and thumbnail (pick a frame or upload an image)",
  "Unpublish/hide a video (keeps chat, comments, and stats) vs. delete it (confirm step; removes the file from Stream and its chat, comments, and playlist entries)",
  "Replace the video file but keep its chat, comments, captions, and link, with an offset adjustment if the new file starts earlier or later",
  "Schedule a video to go public at a date and time; draft videos visible only in Studio",
  "Every change recorded in an audit log (who, what, when)"], ["102"]),
("706", 1, "Must", "M", "Pick videos from the channel to import",
 "As the operator, I want to see every video on the channel and queue the ones I want in one go, without duplicates.",
 ["Studio → Add videos → From the channel: paste a channel link (@handle, /channel/UC…, or a /videos, /streams, /shorts tab), JimBob's channel filled in by default",
  "Lists every video, live stream, and short with thumbnail, title, date, length, and type; newest first; loads all of them (paged, not capped)",
  "Each one shows On the site, Queued, or Not imported; filter Not imported (the default) / All, by type, and a title search",
  "Check boxes plus Select all (of what's showing) and Queue N videos; videos already on the site or queued can't be checked and say so",
  "Pasted links (the current box) that are already on the site say \"You already have this\" with a link to it (already skipped today)",
  "Listing works from Render with a YouTube Data API key (free quota: about 1 unit per 50 videos via the channel's uploads playlist); without a key, the import helper lists the channel with yt-dlp and Studio shows the list when it's back",
  "Tier and \"also import comments\" apply to everything queued in one go"], ["701"]),
("702", 5, "Should", "M", "Chat analytics",
 "As JimBob, I want to see what landed with my audience.",
 ["Messages-per-minute chart per stream with busiest moments linked to timestamps",
  "Top questions and per-stream sentiment summary"], ["102"]),
("703", 1, "Should", "M", "Members and revenue dashboard",
 "As JimBob, I want to see who pays and how much I earn.",
 ["Active members by tier, churn, MRR, tip totals by source"], ["104", "102"]),
("704", 1, "Should", "S", "Data export",
 "As JimBob, I want a copy of everything that's mine.",
 ["CSV export of chat (per video or all), members, and tips"], ["102"]),
("705", 1, "Must", "M", "User management in Studio",
 "As JimBob or a mod, I want to find any member and act on them in one place.",
 ["Users list with search and filters: tier, role, banned, highlighted, new this week; sort by activity",
  "User page: profile, tier and membership, linked YouTube/Rumble names, chat and comment history, notifications sent, mod history",
  "Ban (with reason; blocks sign-in, chat, and comments), time out for a set time, unban; hide all of a user's messages in one step",
  "Highlight a user: VIP/featured badge and name color in chat and comments (e.g. regulars, guests, supporters); remove it any time",
  "Change role (viewer, mod, admin) and, for support cases, tier; private staff notes on the user",
  "Every action logged in mod_actions with who did it; bans and highlights apply live over WebSocket"], ["102", "204"]),
# ---------------- 8 Library & community ----------------
("801", 1, "Must", "M", "Videos dashboard with filters",
 "As a viewer, I want to find videos by type and search, starting from everything.",
 ["Video types from import: regular, short, past live (vertical + short = short; was_live = live)",
  "Filter chips: All, Videos, Shorts, Live, Members only; search and sort (newest, most viewed)",
  "Members-only items show which tier unlocks them; access still enforced on the server"], []),
("802", 1, "Must", "M", "Playlists",
 "As a viewer, I want JimBob's playlists, and as JimBob I want to build my own.",
 ["Import YouTube playlists with their order", "Studio: create, rename, reorder, add/remove videos",
  "Playlists tab lists them with count and total length"], ["801"]),
("803", 1, "Must", "S", "Up next and autoplay",
 "As a viewer, I want the next video to start when one ends.",
 ["Queue beside the player from the playlist (or related videos)", "Autoplay next with a short countdown and cancel",
  "Works in Listen only too"], ["802"]),
("804", 1, "Should", "L", "Posts",
 "As JimBob, I want to post updates, images, and polls; as a member, I want to discuss them.",
 ["Studio composer: text, image, poll", "Posts tab and post page; members-only posts respect tiers",
  "Threaded, quote-aware comments reuse the comments system",
  "Built for how JimBob posts on YouTube (checked 2026-09-30, last 10 posts: all image posts, short or no caption, 400-1,100 likes): multi-photo work-in-progress series (icon painting), memes/comebacks, debate call-outs tagging other creators, personal photos",
  "Platform extras shown in the preview on /posts: polls, stream links with the video card, members-only posts (blurred and locked below the tier), store drops with the product card, Q&A calls",
  "Import: YouTube's Posts page includes the latest ~10 posts in its page data; older posts need paging through its continuation requests (yt-dlp doesn't import posts)"], []),
("805", 1, "Should", "S", "Live indicator",
 "As a viewer, I want to see at a glance when JimBob is live.",
 ["Red ring + LIVE badge on JimBob's avatar and the header when live", "Live card at the top of Videos",
  "Studio Go live switch pointing at the YouTube live URL until MBJ-301 detects it automatically",
  "When not live, show the next stream from the schedule (weekdays around 12:00pm ET)"], []),
("806", 4, "Should", "M", "Import the whole channel",
 "As the operator, I want to load JimBob's full library in one run.",
 ["Import from a Google Takeout folder (match by YouTube ID from the metadata) or the channel list",
  "Proposes file-to-video matches for review; OBS recordings matched by date and length with an offset adjustment",
  "Skips videos already imported; deletes local copies after upload; resumable overnight run"], ["506"]),
("807", 1, "Should", "M", "Store (Shopify integration)",
 "As a fan, I want to browse and buy JimBob's merch without leaving his platform's look and feel.",
 ["Decision: keep the existing Shopify store (madebyjimbob.com, ~150 products) for catalog, checkout, and fulfilment",
  "Shop section shows the store's collections and products live (public product JSON, 10-minute cache); Buy opens the product in the store",
  "Next: cart and checkout inside the platform with Shopify's Storefront API (needs a Storefront access token from JimBob's Shopify admin)",
  "Member and founding-member discount codes applied at checkout",
  "Revisit moving merch off Shopify (own Stripe checkout + print-on-demand) if MBJ-112 shows a real saving"], []),
("808", 2, "Should", "S", "Art section",
 "As a fan, I want to browse JimBob's illustrations and comics.",
 ["Gallery built from the store's art collections (original art, art prints, classic art prints, digital art)",
  "Tap a piece to see it large; View in store buys the print", "Filter by kind of art",
  "Later: link pieces to the videos and posts they appear in"], ["807"]),
("809", 1, "Should", "S", "Social media links and sharing",
 "As JimBob, I want my socials everywhere and every page easy to share.",
 ["Links to JimBob's YouTube, X, Instagram, Facebook, Gab, Telegram, Spotify, Bandcamp (and Rumble) on the Videos banner (done), header menu, and footer",
  "Share button on videos, moments (?t=), comments, and playlists; copies a link or opens the phone's share sheet",
  "Open Graph and Twitter card previews with title, thumbnail, and description"], []),
("810", 1, "Must", "M", "Navigation bar",
 "As a viewer, I want to find every part of the site quickly on desktop and phone.",
 ["Top navigation: Videos, Playlists, Posts, Live, Store, Art, Members, with the live ring (MBJ-805)",
  "Phone and installed app: bottom tab bar with the main sections", "Account menu: profile, notifications, membership, Studio for admins, sign out",
  "Keyboard and screen-reader friendly"], []),
("811", 1, "Should", "M", "Founding members",
 "As an early supporter, I want to be recognised as a founding member.",
 ["Limited founding membership (count or date window) with a price locked for life",
  "Founding badge in chat and comments; founding members page (wall) with opt-in names",
  "Perks defined with JimBob (early access, store discount, call-in priority)"], ["104"]),
("813", 1, "Should", "M", "Schedule calendar with export",
 "As JimBob, I want to publish my stream and debate schedule; as a viewer, I want it in my own calendar.",
 ["Studio: add, edit, and cancel events: stream, debate, guest appearance, premiere, members-only event; title, description, guests, start time with time zone, expected length, and the YouTube (or site) link",
  "Recurring events (e.g. weekday streams around 12:00pm ET) with one-off changes and cancellations",
  "Schedule page: upcoming list and month view shown in the viewer's own time zone, with countdowns; members-only events respect tiers",
  "Export: Add to calendar per event (Google, Apple, Outlook via an .ics file) and a subscribe link (webcal/ICS feed) that keeps a viewer's calendar updated automatically",
  "Remind me: push and in-site notification before an event starts (MBJ-214), and at go-live",
  "Feeds the live indicator's \"Next stream\" (MBJ-805) and can post an announcement to Posts (MBJ-804)"], []),
("814", 1, "Should", "S", "Unwatched filter and binge queue",
 "As a viewer, I want to see what I haven't watched and play it all back to back.",
 ["Filter chips on Videos: Unwatched, In progress, Watched (from watch progress; account when signed in, browser otherwise)",
  "Binge queue: an automatic playlist of everything you haven't finished, in-progress first then oldest to newest (or newest first), that plays with Up next and autoplay, in Listen only too",
  "Mark as watched / unwatched from a video's menu; finishing a video (last 30s) marks it watched",
  "Counts on the chips and a \"Keep watching\" row on the Videos page"], ["212", "803"]),
("815", 1, "Must", "M", "Technical SEO",
 "As JimBob, I want Google and link previews to understand every page, so people find the platform instead of only YouTube.",
 ["The server fills in each page's title, description, canonical URL, and Open Graph/Twitter tags before sending it (the app is client-rendered, so today crawlers and link previews see the same empty page for every video)",
  "Crawlers get the real content in the HTML for public pages: video title, description, chapters, and a transcript excerpt (prerender or server-render the public pages)",
  "Structured data (JSON-LD): VideoObject for each video (thumbnail, upload date, duration, views, embed URL), key moments from chapters, BroadcastEvent for live streams, Event for scheduled streams and debates (MBJ-813), Person/Organization for JimBob with his social profiles",
  "sitemap.xml (videos, playlists, posts, topic and guest pages) and robots.txt; members-only content and Studio are noindex",
  "Real 404 status for missing pages (today every address returns 200) and 301 redirects for moved ones",
  "Keep the madebyjimbob.onrender.com preview out of search (noindex) until the real domain is chosen (ADR-011), then redirect it to the canonical domain",
  "Speed: split the JavaScript bundle (currently one ~500 KB file), long cache headers for hashed assets, lazy images; check Core Web Vitals",
  "Google Search Console and Bing Webmaster Tools verified; sitemap submitted"], ["809"]),
("816", 1, "Should", "M", "Search-friendly content",
 "As a fan searching Google for a debate, guest, or topic, I want to land on JimBob's platform.",
 ["Readable URLs with slugs (e.g. /watch/4/evolution-debate, /playlist/5/debates); old numeric URLs redirect",
  "Each video page has a unique written summary and chapters (from MBJ-605) and an indexable transcript section (public videos only)",
  "Topic and guest pages (MBJ-609) as landing pages: \"JimBob on evolution\", \"JimBob vs <guest>\", with every related moment",
  "Internal links between related videos, topics, guests, playlists, and posts",
  "YouTube and social descriptions link back to the matching platform page (distribution, not just SEO)",
  "Track which searches bring people in (Search Console) in the Studio dashboard"], ["815", "605", "609"]),
("817", 1, "Should", "S", "Friends of the channel",
 "As JimBob, I want to point my audience to the creators, guests, and partners I recommend.",
 ["Studio: add, edit, reorder, and remove friends: name, photo, one-line description, and links (YouTube, X, Rumble, website, store)",
  "Friends page, plus a short row on the Videos banner and a link in the navigation (MBJ-810)",
  "Each friend links to the streams they appear in once guests are tagged (MBJ-608, MBJ-609)",
  "Sponsors and affiliate links clearly labeled as such; external links open in a new tab",
  "Friends can be shown in the stream notes and on topic/guest pages"], []),
("812", 1, "Must", "S", "JimBob's brand on the platform",
 "As JimBob, I want the platform to look like my brand, not a template.",
 ["Store teal (#27717A) as the accent color; MADEbyJIMBOB wordmark in Jost (the store's font)",
  "JimBob's illustrated avatar in the header and as the app icon; his banner art on the Videos page",
  "Stream schedule and social links on the Videos banner",
  "Brand assets copied from madebyjimbob.com into web/public/brand with JimBob's approval"], []),
]

PHASES = {0: "Phase 0 — Foundation", 1: "Phase 1 — VOD platform", 2: "Phase 2 — Mobile",
          3: "Phase 3 — Live via YouTube", 4: "Phase 4 — Owned live + audio", 5: "Phase 5 — Engagement"}

SPRINTS = [
    ("Sprint 1", "Foundation", ["001", "002", "003", "005", "006", "306"]),
    ("Sprint 2", "Real users", ["101", "102", "007", "201"]),
    ("Sprint 3", "Paid tiers", ["103", "104", "105", "107"]),
    ("Sprint 4", "Chat that scales socially", ["204", "203", "202", "209"]),
    ("Sprint 5", "Shared types + mobile start", ["004", "401", "402"]),
    ("Sprint 6", "Mobile core", ["403", "404", "406"]),
    ("Sprint 7", "Go live", ["301", "205", "302", "303"]),
    ("Next", "Presence and navigation", ["805", "810", "809", "804"]),
    ("Then", "Accounts and money", ["101", "114", "108", "113", "106", "116", "117", "115", "118", "119", "104", "109", "105", "811", "807"]),
]

# Story status lives here, not in BACKLOG.md (that file is regenerated). Example: {"001": "Done"}
STATUS = {"001": "Done", "002": "Done", "003": "Done", "005": "In progress", "006": "Done", "007": "Done",
          "201": "Done", "202": "Done", "210": "Done", "801": "Done", "802": "Done", "803": "Done", "807": "In progress", "808": "Done",
          "809": "In progress", "812": "Done", "815": "In progress", "613": "In progress", "211": "Done", "212": "Done", "213": "Done",
          "214": "Done", "604": "In progress", "114": "In progress", "101": "Done", "108": "In progress", "113": "Done", "106": "Done", "110": "In progress", "118": "Done", "215": "Done", "701": "In progress", "102": "In progress"}
# 202: @ suggestions, in-site notifications (bell, bubble, jump to moment); push is MBJ-214.
# 214: live once VAPID_PRIVATE_KEY is set on Render.
# 613: thumbs up/down shipped; moment reactions and hotspots remain.
# 815: per-page titles/previews, real 404s, noindex, bundle splitting and caching shipped; crawlable content, JSON-LD, sitemap remain.
# 604: Stream auto-captions + transcripts table + captions:fetch done; mobile player and Whisper (for R2) remain.
# 114: sending, templates, send log, bounce webhook, and Studio preview/test done; DNS on JimBob's domain + Render keys remain.
# 101: Better Auth on our tables; email + password, username at sign-up, cookie sessions, POC /session gone, tiers not selectable.
# 108: sign-up dialog, username rules, reserved/banned names, 13+ box, verification email, leaked-password check, POC accounts asked for an email done; /join page, live username suggestions, Turnstile remain.
# 113: forgot/reset, change password, change email (password + confirm new + 7-day undo to old), rate limits, security history.
# 106: /account with profile, sign-in and security (email, password, devices, activity), notification settings, membership matrix; profile editor, billing, and data/deletion arrive with MBJ-117, 104, 118.
# 118: export JSON, delete with password, 30-day wait cancelled by signing in, hourly erase, keep-as-"Deleted user" or remove, emails at request and erase. Cancelling paid memberships first joins MBJ-104.
# 215: members enter their YouTube @handle or Rumble name, a moderator confirms in Studio; YouTube matched by channel id (looked up by handle, filled in hourly/after imports); linked messages show site name + tier; @handle mentions notify.
# 701: Studio add (YouTube links queued, import helper on Ruben's PC), replace video file (browser upload to Stream, swap keeps chat), delete (with the Stream file); edit metadata and browser upload of new videos remain.
# 102: users.role + npm run set-role (admin opens Studio); mod role use, Studio role management, /api/mod/* remain.
# 110: device list and sign out any device (in /account) done; Google/Apple/X/Facebook, magic link, passkeys, merging accounts remain.
# 005: workflow is in place; "status check required to merge" needs the GitHub branch rule (README step 5).

def main():
    rows = [dict(id=f"MBJ-{i}", epic=EPICS[i[0]][0], phase=p, priority=pr, size=sz, title=t,
                 story=st, ac=ac, deps=[f"MBJ-{d}" for d in dp], status=STATUS.get(i, "To do"))
            for i, p, pr, sz, t, st, ac, dp in S]

    out = ["# Backlog — MadeByJimBob", "",
           "Generated from `docs/backlog_source.py` — edit there and re-run `python3 docs/backlog_source.py`.",
           "", "**Priority:** Must / Should / Could.  **Size:** S (≤1 day), M (2–3 days), L (~1 week), XL (>1 week).",
           "", "Current state, decisions, and what's next: `docs/STATUS.md`.",
           "", "## Done (POC)", "",
           "- Stored video playback from Cloudflare Stream with gestures, mini player, listen-only, lock-screen metadata",
           "- YouTube import: video → Stream, chat replay → Postgres with `offset_ms`",
           "- Chat replay synced to playback; native posting at playhead with WebSocket broadcast",
           "- Rate limiting, banned-word masking, @mention highlighting",
           "- Tier-gated video detail endpoint; Studio dashboard with per-video access control",
           "", "## Done (MVP hardening)", "",
           "- Username + password sign-in (scrypt); replaced by real accounts in MBJ-101",
           "- Studio restricted to verified `ADMIN_EMAILS` (roles in MBJ-102)",
           "- Chat read, post, and WebSocket join enforce the video's tier",
           "- Malformed or unknown video ids return 400/404 instead of 500",
           "", "## Suggested sprint plan", "", "| Sprint | Goal | Stories |", "|---|---|---|"]
    for name, goal, ids in SPRINTS:
        out.append(f"| {name} | {goal} | {', '.join('MBJ-' + i for i in ids)} |")
    out += ["", "## Summary", "", "| ID | Title | Epic | Phase | Priority | Size | Depends on |", "|---|---|---|---|---|---|---|"]
    for r in sorted(rows, key=lambda r: (r["phase"], r["id"])):
        out.append(f"| {r['id']} | {r['title']} | {r['epic']} | {r['phase']} | {r['priority']} | {r['size']} | {', '.join(r['deps']) or '—'} |")

    for key, (epic, desc) in EPICS.items():
        out += ["", f"## Epic {key}xx — {epic}", "", desc]
        for r in [r for r in rows if r["epic"] == epic]:
            out += ["", f"### {r['id']} — {r['title']}", "",
                    f"**Status:** {r['status']} · **{PHASES[r['phase']]}** · **Priority:** {r['priority']} · **Size:** {r['size']}"
                    + (f" · **Depends on:** {', '.join(r['deps'])}" if r['deps'] else ""),
                    "", r["story"], "", "Acceptance criteria:"]
            box = "x" if r["status"] == "Done" else " "
            out += [f"- [{box}] {a}" for a in r["ac"]]
    with open(ROOT / "BACKLOG.md", "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out) + "\n")

    with open(ROOT / "docs" / "backlog.csv", "w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(["Issue ID", "Summary", "Epic", "Phase", "Priority", "Size", "Status", "Description", "Acceptance Criteria", "Depends On"])
        for r in rows:
            w.writerow([r["id"], r["title"], r["epic"], PHASES[r["phase"]], r["priority"], r["size"], r["status"],
                        r["story"], "\n".join(f"- {a}" for a in r["ac"]), ", ".join(r["deps"])])
    print(f"{len(rows)} stories written")

if __name__ == "__main__":
    main()
